pages:
  image: node
  stage: deploy
  needs: []
  script:
    - cd website
    - yarn install
    - npx docusaurus --version
    - yarn docusaurus clean-api-docs all
    - yarn docusaurus gen-api-docs all
    - yarn build
    - mv ./build ../public
  artifacts:
    paths:
      - public
    expire_in: 2 weeks
  rules:
    - if: $CI_COMMIT_BRANCH != "main"
      when: never
    - when: always

pages-dev:
  image: node
  stage: deploy
  needs: []
  script:
    - cd website
    - yarn install
    - npx docusaurus --version
    - yarn docusaurus clean-api-docs all
    - yarn docusaurus gen-api-docs all
    - yarn build
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: never
    - when: always
